### ISSUE TITLE
App crashes on search action

### ISSUE THREAD

**Issue by shuvashish76** [aloussase/AlexandriaApp#34]
Logs:

```
FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: io.github.aloussase.booksdownloader, PID: 15331
java.net.ConnectException: Failed to connect to libgen.is/:::443
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:859)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:829)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:366)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:353)
	at io.github.aloussase.booksdownloader.services.BookSearchService.startSearch(BookSearchService.kt:99)
	at io.github.aloussase.booksdownloader.services.BookSearchService.access$startSearch(BookSearchService.kt:23)
	at io.github.aloussase.booksdownloader.services.BookSearchService$onStartCommand$1.invokeSuspend(BookSearchService.kt:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@64c076d, Dispatchers.IO]
```
App version: 0.3.5
Android: 9
Model: Lenovo TB-8704X

**Comment by shuvashish76** [comment]
Looks like some blocklist blocking connecting to libgen.is.
I'm using [pdnsf](https://f-droid.org/packages/dnsfilter.android/), but the app shouldn't crash either.

**Comment by aloussase** [comment]
Thanks for the report
